#+TITLE: Getting Started Guide
#+STARTUP: nofold

GNU Emacs is one grand ol' adventure, let alone Doom Emacs. Before you start
you'll need to set up Emacs, Doom, and its packages, then learn how to take care
of your new puppy/operating system. This guide will walk you through installing,
using, configuring and troubleshooting all of these things, to smooth you into
your Emacs journey.

This guide will gloss over many technicalities so you can get up and running as
soon as possible. A more technical user manual is in the works for aspiring
contributors who want a deeper understanding of how Doom Emacs works.

#+begin_quote
If you feel like we've missed something, [[https://discord.gg/qvGgnVx][join us on our Discord server]] and let
us know!
#+end_quote

* Table of Contents :TOC_4:
- [[#install][Install]]
 - [[#emacs--dependencies][Emacs & dependencies]]
 - [[#on-linux][On Linux]]
 - [[#ubuntu][Ubuntu]]
 - [[#fedora][Fedora]]
 - [[#arch-linux][Arch Linux]]
 - [[#nixos][NixOS]]
 - [[#opensuse][openSUSE]]
 - [[#gentoo-linux][Gentoo Linux]]
 - [[#on-macos][On macOS]]
 - [[#with-homebrew][With Homebrew]]
 - [[#with-macports][With MacPorts]]
 - [[#on-windows][On Windows]]
 - [[#with-chocolatey--scoop][With chocolatey / scoop]]
 - [[#with-a-precompiled-binary--git-bash][With a precompiled binary + Git Bash]]
 - [[#with-wsl--ubuntu-1804-lts][With WSL + Ubuntu 18.04 LTS]]
 - [[#doom-emacs][Doom Emacs]]
 - [[#the-bindoom-utility][The ~bin/doom~ utility]]
 - [[#install-doom-manually][Install Doom Manually]]
 - [[#install-doom-alongside-other-configs-with-chemacs2][Install Doom alongside other configs (with Chemacs2)]]
 - [[#externalsystem-dependencies][External/system dependencies]]
- [[#update--rollback][Update & Rollback]]
 - [[#rollback][Rollback]]
 - [[#updowngrading-emacs][Up/Downgrading Emacs]]
- [[#migrate][Migrate]]
 - [[#from-vanilla-emacs][From vanilla Emacs]]
 - [[#from-spacemacs][From Spacemacs]]
- [[#configure][Configure]]
 - [[#modules][Modules]]
 - [[#package-management][Package management]]
 - [[#installing-packages][Installing packages]]
 - [[#installing-packages-from-external-sources][Installing packages from external sources]]
 - [[#pinning-packages-to-specific-commits][Pinning packages to specific commits]]
 - [[#disabling-packages][Disabling packages]]
 - [[#changing-a-recipe-for-an-included-package][Changing a recipe for an included package]]
 - [[#usingloading-local-packages][Using/loading local packages]]
 - [[#configuring-doom][Configuring Doom]]
 - [[#configuring-packages][Configuring packages]]
 - [[#reloading-your-config][Reloading your config]]
 - [[#binding-keys][Binding keys]]
 - [[#writing-your-own-modules][Writing your own modules]]
 - [[#file-structure][File structure]]
 - [[#initel][=init.el=]]
 - [[#configel][=config.el=]]
 - [[#packagesel][=packages.el=]]
 - [[#autoloadel-or-autoloadel][=autoload/*.el= OR =autoload.el=]]
 - [[#doctorel][=doctor.el=]]
 - [[#cliel][=cli.el=]]
 - [[#testtest-el][=test/**/test-*.el=]]
 - [[#additional-files][Additional files]]
 - [[#load-order][Load order]]
 - [[#flags][Flags]]
 - [[#doom-cookies][Doom cookies]]
 - [[#if][~;;;###if~]]
 - [[#package][~;;;###package~]]
 - [[#autodef][~;;;###autodef~]]
 - [[#common-mistakes-when-configuring-doom-emacs][Common mistakes when configuring Doom Emacs]]
 - [[#packages-are-eagerly-loaded][Packages are eagerly loaded]]
 - [[#manual-package-management][Manual package management]]
 - [[#using-org-babel-do-load-languages-to-load-your-babel-packages][Using ~org-babel-do-load-languages~ to load your babel packages]]
 - [[#using-delete-trailing-whitespaces-or-whitespace-cleanup-to-manage-leftover-whitespace][Using ~delete-trailing-whitespaces~ or ~whitespace-cleanup~ to manage leftover whitespace]]
- [[#troubleshoot][Troubleshoot]]
 - [[#looking-up-documentation-and-state-from-within-emacs][Looking up documentation and state from within Emacs]]
 - [[#variables-functions-faces-etc][Variables, functions, faces, etc.]]
 - [[#for-doom-modules-packages-autodefs-etc][For Doom Modules, packages, autodefs, etc.]]
 - [[#how-to-extract-a-backtrace-from-an-error][How to extract a backtrace from an error]]
 - [[#enabling-debug-on-error][Enabling ~debug-on-error~]]
 - [[#a-backtrace-from-bindoom][A backtrace from ~bin/doom~]]
 - [[#evaluating-elisp-on-the-fly][Evaluating Elisp on-the-fly]]
 - [[#how-to-determine-the-origin-of-a-bug][How to determine the origin of a bug]]
 - [[#testing-in-dooms-sandbox][Testing in Doom's sandbox]]
 - [[#opening-the-sandbox][Opening the sandbox]]
 - [[#launching-the-sandbox][Launching the sandbox]]
 - [[#testing-packages-in-the-sandbox][Testing packages in the sandbox]]
 - [[#bisecting-your-private-config][Bisecting your private config]]
 - [[#bisecting-doom-emacs][Bisecting Doom Emacs]]

* Install
This is what you'll have installed by the end of this section:

- Git 2.23+
- Emacs 27.1+ *(27.2 is recommended, or [[https://www.emacswiki.org/emacs/GccEmacs][native-comp]])*
- [[https://github.com/BurntSushi/ripgrep][ripgrep]] 11.0+
- GNU Find
- (Optional) [[https://github.com/sharkdp/fd][fd]] 7.3.0+ (known as ~fd-find~ on Debian, Ubuntu & derivatives) --
 improves performance for many file indexing commands

These packages ought to be available through the package managers of your
operating system; i.e. homebrew & macports on macOS, scoop/chocolatey on
Windows, or pacman/aptitude/etc on the various Linux distributions.

** Emacs & dependencies
*** On Linux
Installation instructions for Emacs 27.1+ are listed below for many popular
Linux distributions. In the unusual case that 27.1 or newer is unavailable on
your system, you'll have to [[https://www.gnu.org/software/emacs/manual/html_node/efaq/Installing-Emacs.html][build it from source]] instead.

**** Ubuntu
Emacs 27.x is not available through Ubuntu's package manager out-of-the-box, but
is available through a PPA:

#+BEGIN_SRC bash
add-apt-repository ppa:kelleyk/emacs
apt-get update
apt-get install emacs27
#+END_SRC

Or through snap:

#+BEGIN_SRC bash
snap install emacs --classic
#+END_SRC

In some cases, you may need to delete old version of emacs and it's dependencies first, before installing emacs27:
#+BEGIN_SRC bash
sudo apt remove emacs
sudo apt autoremove
#+END_SRC

***** Other dependencies
Then install Doom's other dependencies:
#+BEGIN_SRC bash
apt-get install ripgrep fd-find

# On 18.04 or older, ripgrep and fd-find won't be available in
# official repos. You'll need to install them another way, e.g.
sudo dpkg -i fd_8.2.1_amd64.deb # adapt version number and architecture
sudo dpkg -i fd_8.2.1_amd64.deb # adapt version number and architecture
#+END_SRC

**** Fedora
#+BEGIN_SRC bash
# required dependencies
dnf install emacs git ripgrep
# optional dependencies
dnf install fd-find # is 'fd' in Fedora <28
#+END_SRC

**** Arch Linux
#+BEGIN_SRC bash
# required dependencies
pacman -S git emacs ripgrep
# optional dependencies
pacman -S fd
#+END_SRC

The above installs Emacs 27 (at the time of writing).

**** NixOS
On NixOS Emacs 27.2 can be installed via ~nix-env -Ai nixos.emacs~, or
permanently with the following added to ~etc/nixos/configuration.nix~:

#+BEGIN_SRC nix
environment.systemPackages = with pkgs; [
 # required dependencies
 git
 emacs # Emacs 27.2
 ripgrep
 # optional dependencies
 coreutils # basic GNU utilities
 fd
 clang
];
#+END_SRC

Installing Emacs 28+ will require [[https://github.com/nix-community/emacs-overlay/issues][nix-community/emacs-overlay]]:
#+BEGIN_SRC nix
nixpkgs.overlays = [
 (import (builtins.fetchTarball https://github.com/nix-community/emacs-overlay/archive/master.tar.gz))
];

environment.systemPackages = [
 pkgs.emacsGcc # Installs Emacs 28 + native-comp
];
#+END_SRC

**** openSUSE
***** Emacs 27.1
Emacs can be installed from the [[https://software.opensuse.org/download.html?project=editors&package=emacs][package list]], or manually via zypper.

For example, to install on openSUSE Leap 15.1 (requires root):
#+BEGIN_SRC bash
zypper addrepo https://download.opensuse.org/repositories/editors/openSUSE_Leap_15.1/editors.repo
zypper refresh
zypper install emacs
#+END_SRC

If you already have an older version of Emacs installed, you will be prompted to
install the update candidate (Emacs 27.1).

***** ripgrep
Download ripgrep 11.0.2 from [[https://software.opensuse.org/download/package?package=ripgrep&project=openSUSE%3AFactory][the package list]] or installed manually (requires
root).
#+BEGIN_SRC bash
zypper addrepo https://download.opensuse.org/repositories/openSUSE:Factory/standard/openSUSE:Factory.repo
zypper refresh
zypper install ripgrep
#+END_SRC

Only ripgrep 0.8.1 is officially available on Leap 15.1 and 15.2, so you will
need to install Rust to build ripgrep from source. Rust can be downloaded [[https://software.opensuse.org/package/rust][from
the package list]] or installed manually via zypper (requires root), e.g.
#+BEGIN_SRC bash
zypper addrepo https://download.opensuse.org/repositories/openSUSE:Leap:15.1:Update/standard/openSUSE:Leap:15.1:Update.repo
zypper refresh
zypper install rust
#+END_SRC

See the [[https://github.com/BurntSushi/ripgrep#building][ripgrep documentation]] for instructions on building from source.

**** Gentoo Linux
Everything you need is in Gentoo's official =::gentoo= repository.

***** Emacs
To use Emacs graphically, enable the =gui= USE flag. And enable the =xft= USE flag to render fonts correctly (see
[[https://github.com/hlissner/doom-emacs/issues/4876][issue #4876]])
#+begin_src sh
echo "app-editors/emacs gui xft" >> /etc/portage/package.use/emacs
#+end_src

To install the latest unmasked version compatible with Doom:
#+begin_src sh
emerge '>=app-editors/emacs-27.0'
#+end_src

Or, for GCCEmacs/Native Compilation, use the live ebuild for version 28.0 with the =jit= USE flag:

Unmask the desired ebuild by adding the following to =package.accept_keywords=:
#+begin_src
=app-editors/emacs-28.0.9999 **
#+end_src

Add the =jit= USE flag to =package.use=:
#+begin_src
=app-editors/emacs-28.0.9999 jit
#+end_src

And emerge:
#+begin_src sh
emerge =app-editors/emacs-28.0.9999
#+end_src

***** Other Dependencies
#+begin_src sh
# required
emerge '>=dev-vcs/git-2.23' '>=sys-apps/ripgrep-11.0' sys-apps/findutils
# optional
emerge '>=sys-apps/fd-7.3.0'
#+end_src

*** On macOS
MacOS users have many options for installing Emacs, but not all of them are well
suited to Doom. Before we get to that you'll need either the Homebrew or
MacPorts package manager installed (you only need one):

+ [[http://brew.sh/][How to install Homebrew]]
+ [[https://www.macports.org/install.php][How to install MacPorts]]

**** With Homebrew
First, Doom's dependencies:
#+BEGIN_SRC bash
# required dependencies
brew install git ripgrep
# optional dependencies
brew install coreutils fd
# Installs clang
xcode-select --install
#+END_SRC

For Emacs itself, these three formulas are the best options, ordered from most
to least recommended for Doom (based on compatibility).

- [[https://bitbucket.org/mituharu/emacs-mac/overview][emacs-mac]]. It offers good integration
 with macOS, native emojis and better childframe support.
 #+BEGIN_SRC bash
 brew tap railwaycat/emacsmacport
 brew install emacs-mac --with-modules
 ln -s /usr/local/opt/emacs-mac/Emacs.app /Applications/Emacs.app
 #+END_SRC

- [[https://github.com/d12frosted/homebrew-emacs-plus][emacs-plus]]. Some users have
 experienced [flashing artifacts when scrolling](https://github.com/d12frosted/homebrew-emacs-plus/issues/314):
 #+BEGIN_SRC bash
 brew tap d12frosted/emacs-plus
 brew install emacs-plus
 ln -s /usr/local/opt/emacs-plus/Emacs.app /Applications/Emacs.app
 #+END_SRC

- [[https://formulae.brew.sh/formula/emacs][emacs]] is another acceptable option, **but does not provide a Emacs.app**:
 #+BEGIN_SRC bash
 brew install emacs
 #+END_SRC

***** Where *not* to install Emacs from
These builds/forks have known compatibility issues with Doom and are *very
likely* to cause issues later on. They are not recommended:

+ emacsformacosx.com
+ ~brew cask install emacs~ (installs from emacsformacosx.com)
+ AquaMacs
+ XEmacs

**** With MacPorts
There are four ports (at time of writing) available through MacPorts, and they
are all acceptable options:

+ [[https://ports.macports.org/port/emacs/summary][emacs]] (27.2) and [[https://ports.macports.org/port/emacs-devel/summary][emacs-devel]] (28) -- Installs terminal-only Emacs
+ [[https://ports.macports.org/port/emacs-app/summary][emacs-app]] (27.2), [[https://ports.macports.org/port/emacs-app-devel/summary][emacs-app-devel]] (28) -- Installs GUI Emacs
+ [[https://ports.macports.org/port/emacs-mac-app/summary][emacs-mac-app]] (27.2) -- the [[https://bitbucket.org/mituharu/emacs-mac][Mitsuharu Yamamoto mac port]]

Some of these ports do not add an =emacs= binary to your ~PATH~, which is
necessary for Doom's installation process. You'll have to do so yourself by
adding this to your shell config:

#+BEGIN_SRC sh
# Add this to ~/.zshrc or ~/.bash_profile
export PATH="/Applications/MacPorts/Emacs.app/Contents/MacOS:$PATH"
#+END_SRC

Or by replacing ~/usr/local/bin/emacs~ with a shim script containing:
#+BEGIN_SRC
#!/bin/sh
/Applications/MacPorts/Emacs.app/Contents/MacOS/Emacs "$@"
#+END_SRC

*** On Windows
#+begin_quote
*WARNING:* Emacs on Windows is much slower than its Linux or macOS counterparts.
There are some suggestions on how to speed it up later in this section.
#+end_quote

There are three methods for installing Emacs 27.x on Windows, each with their
pros and cons:

+ With chocolatey/scoop
+ With a precompiled binary + Git Bash
+ With WSL2 + Ubuntu

If you don't know which to choose, I highly recommend WSL; it produces the
fastest and most stable environment of the three, but has the most complex
installation process.

Before moving on to installing Emacs et co, a few steps to prepare Windows for
Emacs are necessary:

1. Create a ~HOME~ [[https://mywindowshub.com/how-to-edit-system-environment-variables-for-a-user-in-windows-10/][system environment variable]].

 Set it to =C:\Users\USERNAME\=, otherwise Emacs will treat
 =C:\Users\USERNAME\AppData\Roaming= as your ~HOME~, which will cause issues
 later.

2. Add =C:\Users\USERNAME\.emacs.d\bin= to your ~PATH~.

 This way, you don't have to type all of =C:\Users\USERNAME\.emacs.d\bin\doom=
 every time you need to run this script (and you'll need to, often).

 #+begin_quote
 A pre-existing PATH variable should already exist among your system
 variables. It contains a string of file paths separated by colons;
 ~pathA:pathB:pathC~. Prepend the path to bin/doom to that string, like so:
 ~C:\Users\username\.emacs.d\bin:pathA:pathB:pathC~
 #+end_quote

3. Restart your system so your new values for ~HOME~ and ~PATH~ take effect.

Now we're ready to move on!

[... truncated ...]