# SwiftLint configuration for Oppi
# Practical rules — catch real issues, not style nitpicks

included:
  - Oppi
  - OppiTests
  - Shared

excluded:
  - Oppi.xcodeproj
  - .build

# Disable noisy rules that don't catch real bugs
disabled_rules:
  - trailing_comma # Swift allows trailing commas, consistent style
  - identifier_name # Short names (i, c, n) are fine in loops/closures
  - implicit_optional_initialization
  - file_length
  - line_length
  - function_body_length
  - type_body_length
  - cyclomatic_complexity
  - function_parameter_count
  - nesting
  - blanket_disable_command # Allow file-level suppressions for tests/fixtures

# Opt-in rules worth enabling
opt_in_rules:
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_first_not_nil
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - fatal_error_message
  - first_where
  - force_unwrapping
  - last_where
  - literal_expression_end_indentation
  - modifier_order
  - overridden_super_call
  # - pattern_matching_keywords  # too noisy — revisit later
  - prefer_self_in_static_references
  - prefer_self_type_over_type_of_self
  - private_action
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture

# Analyzer-only rules (run under `swiftlint analyze`)
analyzer_rules:
  - unused_declaration
  - unused_import

# Force casts/tries — warn (sometimes necessary for Codable/UIKit)
force_cast:
  severity: warning

force_try:
  severity: warning

force_unwrapping:
  severity: warning

empty_count:
  severity: warning

enum_case_associated_values_count:
  warning: 7
  error: 10
